#include <iostream>
#include <cmath>
using namespace std;

int main()
{
    int q, alpha;
    double XA, XB;

    cout << "Enter the prime number: ";
    cin >> q;
    cout << "Enter the primitive root: ";
    cin >> alpha;
    cout << "User A, enter the private key: ";
    cin >> XA;
    cout << "User B, enter the private key: ";
    cin >> XB;

    double YA = fmod(pow(alpha, XA), q);
    double YB = fmod(pow(alpha, XB), q);

    cout << "The PUBLIC key generated for User A is: " << YA << endl;
    cout << "The PUBLIC key generated for User B is: " << YB << endl;

    double KA = fmod(pow(YB, XA), q);
    double KB = pow(YA, XB);
    double AKB = fmod(KB, q);

    cout << "The secret key generated by User A: " << KA << endl;
    cout << "The secret key generated by User B: " << AKB << endl;

    return 0;
}
